name: eventWorkflow_schedule1

on:
  schedule:
    - cron: "15 15 * * *"
jobs:
  even_demo:
    runs-on: ubuntu-latest
    steps:
      - name: trigger_workflow
        run: echo "trigger workflow"
      
