name: show_repo_secret_var_example

on:
  workflow_dispatch:

jobs:
  secret_demo:
    runs-on: ubuntu-latest
    steps:
      - name: show_repo_var
        run: echo "repo variable = ${{vars.API_KEY_REPO_VAR }}"
      - name: show_secret_var
        env:
          secret_var: ${{secrets.API_KEY_REPO_SECRET}}
        run: |
            echo "we got the secret from repo"
            echo "secret value = $secret_var"


